services:
  postgres:
    image: postgres:14
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simba_db
    ports:
      - 5432:5432
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

steps:
  - name: Checkout code (if needed)
    uses: actions/checkout@v3

  - name: Wait for Postgres to be ready
    run: |
      for i in {1..10}; do
        pg_isready -h localhost -p 5432 -U postgres && break
        sleep 2
      done

  - name: Install PostgreSQL client
    run: sudo apt-get update && sudo apt-get install -y postgresql-client

  - name: Create employees table
    run: |
      PGPASSWORD=password psql -h localhost -U postgres -d simba_db -c "
      CREATE TABLE employees (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        position VARCHAR(50),
        salary NUMERIC
      );"

  - name: Insert sample data
    run: |
      PGPASSWORD=password psql -h localhost -U postgres -d simba_db -c "
      INSERT INTO employees (name, position, salary) VALUES
      ('Alice', 'Developer', 5000),
      ('Bob', 'Designer', 4500),
      ('Charlie', 'Manager', 6000);"

  - name: Query data from employees table
    run: |
      echo "Fetching all employees:"
      PGPASSWORD=password psql -h localhost -U postgres -d simba_db -c "SELECT * FROM employees;"
